### ISSUE TITLE
Memory consumption on CIFAR-10

### ISSUE THREAD

**Issue by WinterPan2017** [locuslab/deq#19]
Hello, When I trained the tiny MDEQ model on cifar10(The batch size was set to 32), the memory usage was 2099MB on a single RTX3090. But the paper says it is 0.7GB. How could I reproduce it?

Below are the details of the configuration file I use.
```
GPUS: (0,)
LOG_DIR: 'log/'
DATA_DIR: ''
OUTPUT_DIR: 'output/'
WORKERS: 2
PRINT_FREQ: 100

MODEL: 
  NAME: mdeq
  NUM_LAYERS: 10
  NUM_CLASSES: 10
  NUM_GROUPS: 8
  DROPOUT: 0.25
  WNORM: true
  DOWNSAMPLE_TIMES: 0
  EXPANSION_FACTOR: 5
  POST_GN_AFFINE: false
  IMAGE_SIZE: 
    - 32
    - 32
  EXTRA:
    FULL_STAGE:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      BIG_KERNELS:
      - 0
      - 0
      HEAD_CHANNELS:
      - 8
      - 16
      FINAL_CHANSIZE: 200
      NUM_BLOCKS:
      - 1
      - 1
      NUM_CHANNELS:
      - 24
      - 24
      FUSE_METHOD: SUM
DEQ:
  F_SOLVER: 'broyden'
  B_SOLVER: 'broyden'
  STOP_MODE: 'rel'
  F_THRES: 18
  B_THRES: 20
  SPECTRAL_RADIUS_MODE: false
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
LOSS:
  JAC_LOSS_WEIGHT: 0.0
DATASET:
  DATASET: 'cifar10'
  DATA_FORMAT: 'jpg'
  ROOT: 'data/cifar10/'
  TEST_SET: 'val'
  TRAIN_SET: 'train'
  AUGMENT: False
TEST:
  BATCH_SIZE_PER_GPU: 32
  MODEL_FILE: ''
TRAIN:
  BATCH_SIZE_PER_GPU: 32
  BEGIN_EPOCH: 0
  END_EPOCH: 50
  RESUME: false
  LR_SCHEDULER: 'cosine'
  PRETRAIN_STEPS: 3000
  LR_FACTOR: 0.1
  LR_STEP:
  - 30
  - 60
  - 90
  OPTIMIZER: adam
  LR: 0.001
  WD: 0.0000025
  MOMENTUM: 0.95
  NESTEROV: true
  SHUFFLE: true
DEBUG:
  DEBUG: false
```

**Comment by shaojieb** [comment]
Hi @WinterPan2017 ,

Thanks for the question. Two reasons:

1) There is inherent memory friction to PyTorch. When you initialize CUDA, the CUDA driver and context take a certain amount of fixed memory for their internal purposes (~800-900MB, depending on the GPU you use).  So e.g., if you set a breakpoint here: https://github.com/locuslab/deq/blob/master/MDEQ-Vision/tools/cls_train.py#L91, you'd already notice a huge chunk of GPU memory allocated (even without running anything). We removed this orthogonal memory consumption from calculation. This is especially important when you measure the memory consumption of small model.

2) The model you run has a pretraining phase (https://github.com/locuslab/deq/blob/master/MDEQ-Vision/lib/models/mdeq_core.py#L428). That is, you are still training a 10-layer network in this phase. Without a `torch.cuda.empty_cache()` operation, that memory will always be shown as "consumed" even though it is not. If you set a breakpoint, you'd find that each layer actually takes ~0.2GB memory. So the 2GB thing you measured was really the consumption of a 10-layer network.

If you are looking for a very memory efficient approach, I also suggest replace f_solver and b_solver with Anderson, rather than Broyden.

Please let me know if this helps!

**Comment by WinterPan2017** [comment]
Hello, @jerrybai1995, Thanks for your help!
1. I followed the first point you said, but I did not see any memory usage at the breakpoint. My PyTorch version is 1.8.1 with the GPU RTX3090. 
2. I set the pertaining steps to 0 in order to avoid the pretraining phase.  The memory usage dropped to 1711MB.
3. I replaced f_solver and b_solver with Anderson and set the pertaining steps to 0. The memory usage is 1647MB.

If I removed this orthogonal memory consumption from the calculation as you said, the experiment is roughly consistent. But I did not see the related memory usage.

**Comment by shaojieb** [comment]
Sorry, for (1), are you setting the breakpoint exactly **on** line 91? That means you have not executed line 91, which initializes CUDA for the model. Could you try setting it to later, such as https://github.com/locuslab/deq/blob/master/MDEQ-Vision/tools/cls_train.py#L213?

Also, could you try setting a breakpoint at https://github.com/locuslab/deq/blob/master/MDEQ-Vision/lib/core/cls_function.py#L75, and run `torch.cuda.memory_allocated()`? This is right before the backward pass takes place, and this function should remove all those contextual GPU costs. I just tried on my end with GPU RTX 2080Ti and am not getting memory cost even as close to the numbers you reported (almost 1.7G) ... I'll look further into this as well. I'm using PyTorch 1.7.0.

Here's the config file I use (shouldn't be different from the one you used, but just in case):
```
GPUS: (0,)
LOG_DIR: 'log/'
DATA_DIR: ''
OUTPUT_DIR: 'output/'
WORKERS: 2
PRINT_FREQ: 100

MODEL: 
  NAME: mdeq
  NUM_LAYERS: 10
  NUM_CLASSES: 10
  NUM_GROUPS: 8
  DROPOUT: 0.25
  WNORM: true
  DOWNSAMPLE_TIMES: 0
  EXPANSION_FACTOR: 5
  POST_GN_AFFINE: false
  IMAGE_SIZE: 
    - 32
    - 32
  EXTRA:
    FULL_STAGE:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      BIG_KERNELS:
      - 0
      - 0
      HEAD_CHANNELS:
      - 8
      - 16
      FINAL_CHANSIZE: 200
      NUM_BLOCKS:
      - 1
      - 1
      NUM_CHANNELS:
      - 24
      - 24
      FUSE_METHOD: SUM
DEQ:
  F_SOLVER: 'broyden'
  B_SOLVER: 'broyden'
  STOP_MODE: 'rel'
  F_THRES: 18
  B_THRES: 20
  SPECTRAL_RADIUS_MODE: false
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
LOSS:
  JAC_LOSS_WEIGHT: 0.0
DATASET:
  DATASET: 'cifar10'
  DATA_FORMAT: 'jpg'
  ROOT: 'data/cifar10/'
  TEST_SET: 'val'
  TRAIN_SET: 'train'
  AUGMENT: False
TEST:
  BATCH_SIZE_PER_GPU: 32
  MODEL_FILE: ''
TRAIN:
  BATCH_SIZE_PER_GPU: 32
  BEGIN_EPOCH: 0
  END_EPOCH: 50
  RESUME: false
  LR_SCHEDULER: 'cosine'
  PRETRAIN_STEPS: 0
  LR_FACTOR: 0.1
  LR_STEP:
  - 30
  - 60
  - 90
  OPTIMIZER: adam
  LR: 0.001
  WD: 0.0000025
  MOMENTUM: 0.95
  NESTEROV: true
  SHUFFLE: true
DEBUG:
  DEBUG: false
```

**Comment by WinterPan2017** [comment]
Sorry, I checked again. As you said, the cuda context takes about 1GB of memory on RTX3090. I will close the issue. Thank you for your patience.
