### ISSUE TITLE
UnboundLocalError: local variable 'lowest_xest' referenced before assignment                                                                     

### ISSUE THREAD

**Issue by wang-zm18** [locuslab/deq#26]
Aftering training normally for several epochs, it occurs this problem for the anderson solver. This error corresponds to the Line 251 in solvers.py.

**Comment by Gsunshine** [comment]
Hi @wang-zm18,

Thank you for your interest in DEQ! Regarding your question, you can add this line before line 221 in solver.py.

`lowest_xest = x0`

Given this error, it might mean the solver converges very poorly. I will suggest monitoring the convergence in your model. You may find the convergence log in the tensorboard. (These statistics should be already recorded in the tensorboard writer.)

Thanks.

**Comment by Gsunshine** [comment]
BTW, this repo will be upgraded in the near future, improving most training issues and stability. You may expect this update.

Thanks.

**Comment by shaojieb** [comment]
Hi @wang-zm18,

Adding to @Gsunshine 's answer above, you can also try regularizing the model (with Jaocbian regularization), or Broyden's method. It seems indeed that this error arose because of some extreme instability, and we may be able to better help you if you can provide the convergence log/trace.

**Comment by wang-zm18** [comment]
OK， thanks for your kind help!
